
name: Run MATLAB Script on GitHub-Hosted Runner
on: push
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: version          
      - name: Run Tests
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: src
