name: Tests 22a
on: [push]
jobs:
  my-job:
    name: Tests22a
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
            release: R2022a
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: edit add
